/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_wages;

import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author MadinaJute
 */
public class DepartmentRangeReport extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    private String parent = "";
    private HashMap parameter;
    private static Connection connection;
    private String fromDate;
    private String toDate;
    DefaultComboBoxModel dm = new DefaultComboBoxModel();
    DefaultComboBoxModel dm2 = new DefaultComboBoxModel();
    private String departmentFrom;
    private String runningShift;
    private String oriShift;
    private String departmentTo;
    private int totalInNumber;
    private String totalInWords;
    private int sumOfPending;
    private int sumOfNetPay;
    private String cardNo;
    
    public DepartmentRangeReport() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        connection=DBconnect.dbconnect();
         getDepartmentFrom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runningWeekCb = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        weekEndDC = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ori_shift_com = new javax.swing.JComboBox<>();
        run_shift_com = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        departmentFromCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        departmentToCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cardNoTF = new javax.swing.JTextField();
        reportPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        runningWeekCb.setSelected(true);
        runningWeekCb.setText("Runing Week");
        runningWeekCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runningWeekCbActionPerformed(evt);
            }
        });

        jLabel1.setText("Week End Date");

        weekEndDC.setEnabled(false);

        jLabel2.setText("Original Shift");

        jLabel3.setText("Running Shift");

        ori_shift_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "A", "B", "C" }));
        ori_shift_com.setEnabled(false);

        run_shift_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Morning", "Evening", "Night" }));

        jButton2.setText("View Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Department Range (From)");

        departmentFromCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));

        jLabel7.setText("Department Range (To)");

        departmentToCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));

        jButton1.setText("Un-Registered");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Record Inquery");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cardNoTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardNoTFMouseClicked(evt);
            }
        });
        cardNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNoTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ori_shift_com, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runningWeekCb)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weekEndDC, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(run_shift_com, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentFromCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentToCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ori_shift_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run_shift_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(runningWeekCb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(weekEndDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(cardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(departmentFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(departmentToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        reportPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        getContentPane().add(reportPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void runningWeekCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runningWeekCbActionPerformed
        // TODO add your handling code here:
          if (runningWeekCb.isSelected()) {
            weekEndDC.setEnabled(false);
            

        } else {
            weekEndDC.setEnabled(true);
        }
    }//GEN-LAST:event_runningWeekCbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        getMainFilePath();
        getData();
        getTotalInWords();
        getParam();
               
            showReport();
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        getMainFilePath();
        //getData();
        //getTotalInWords();
        getRunningDate();
        getParam_2();
        
       
        reportPanel.removeAll();
        reportPanel.repaint();
        reportPanel.revalidate();       
     
        try {
             JasperDesign jDesign = JRXmlLoader.load(parent+"\\src\\demo_wages\\report\\unregisteredlist.jrxml");
                        JasperReport jReport = JasperCompileManager.compileReport(jDesign);
                        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, connection);
                        JRViewer jRViewer = new JRViewer(jPrint);
                        reportPanel.setLayout(new BorderLayout());
                        reportPanel.add(jRViewer);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //  new ReecordInquery().setVisible(true);
        recordInquery();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cardNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNoTFActionPerformed
        // TODO add your handling code here:
        recordInquery();
    }//GEN-LAST:event_cardNoTFActionPerformed

    private void cardNoTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardNoTFMouseClicked
        // TODO add your handling code here:
        cardNoTF.selectAll();
    }//GEN-LAST:event_cardNoTFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentRangeReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNoTF;
    private javax.swing.JComboBox<String> departmentFromCombo;
    private javax.swing.JComboBox<String> departmentToCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> ori_shift_com;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JComboBox<String> run_shift_com;
    private javax.swing.JCheckBox runningWeekCb;
    private com.toedter.calendar.JDateChooser weekEndDC;
    // End of variables declaration//GEN-END:variables

    private void getMainFilePath() {
        File mainFilePath = new File("AutoRetresh.class");
        File parentLocation = new File(mainFilePath.getAbsolutePath());
        parent = parentLocation.getParent();
        //System.out.println(parent);
    }

    private void getDepartmentFrom() {
        
         departmentFromCombo.removeAllItems();
         departmentToCombo.removeAllItems();
        dm.addElement("Select One");
        dm2.addElement("Select One");
        try {
            String sql = "select * from department ORDER BY department_code ASC";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                dm.addElement(rs.getString("display_name"));
                dm2.addElement(rs.getString("display_name"));
                departmentFromCombo.setModel(dm);
                departmentToCombo.setModel(dm2);
            }
            statement.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
            }

    private void getData() {
        String dptFrom,dptTo;
          if (runningWeekCb.isSelected()) {
            getRunningDate();
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            //fromDate = sdf.format(fromDateDC.getDate().getTime());
            toDate = sdf.format(weekEndDC.getDate().getTime());
        }
          
        dptFrom = departmentFromCombo.getSelectedItem().toString();
        dptTo = departmentToCombo.getSelectedItem().toString();
        
        if(!dptFrom.equals("Select One")){
        departmentFrom=getDepartmentCode(dptFrom);
        }else{
            JOptionPane.showMessageDialog(this, "Please Select Department Range...");
        }
        
         if(!dptTo.equals("Select One")){
        departmentTo=getDepartmentCode(dptTo);
        }else{
            JOptionPane.showMessageDialog(this, "Please Select Department Range...");
        }
        
        runningShift = run_shift_com.getSelectedItem().toString();
        oriShift = ori_shift_com.getSelectedItem().toString();
        System.err.println(fromDate+"\t"+toDate);
            }

    private void getRunningDate() {
         try {
            String sql = "select * from running_week";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                fromDate = rs.getString("week_start_date");
                toDate = rs.getString("week_end_date");
            }
            System.err.println(fromDate + " " + toDate);
            
            statement.close();
            rs.close();
        } catch (SQLException e) {
        }
            }

    private void getParam() {
            parameter = new HashMap();
            parameter.put("ewwkEndDate", toDate);
            parameter.put("oriShift", oriShift);
            parameter.put("runShift", runningShift);
            parameter.put("department_1", departmentFrom);
            parameter.put("department_2", departmentTo);
            parameter.put("totalInWords", totalInWords);
            parameter.put("pendingAmount", String.valueOf(sumOfPending));
            parameter.put("payableAmount", String.valueOf(totalInNumber));
            }

    private void showReport() {
        
        
        reportPanel.removeAll();
        reportPanel.repaint();
        reportPanel.revalidate();
        
        //C:\Users\MadinaJute\OneDrive\Documents\NetBeansProjects\MEGAsync\Demo_Wages\src\demo_wages\report\report1.jrxml
     
        try {
             JasperDesign jDesign = JRXmlLoader.load(parent+"\\src\\demo_wages\\report\\report1.jrxml");
                        JasperReport jReport = JasperCompileManager.compileReport(jDesign);
                        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, connection);
                        JRViewer jRViewer = new JRViewer(jPrint);
                        reportPanel.setLayout(new BorderLayout());
                        reportPanel.add(jRViewer);
        } catch (Exception e) {
            e.printStackTrace();
        }
            }

    private String getDepartmentCode(String dptDisplayName) {
        try {
            String sql="select department_code from department where display_name='"+dptDisplayName+"'";
            PreparedStatement statement= connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if(rs.next()){
                return rs.getString("department_code");
            }else{
                return null;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
           }

    private void getTotalInWords() {
      
        try {
            String sql="select SUM(net_payable) from sallery where r_shift='"+runningShift+"' and "
                    + "r_department  between '"+departmentFrom+"' and '"+departmentTo+"' "
                    + "and week_end_date='"+toDate+"' and block_status <>1";
            PreparedStatement statement=connection.prepareStatement(sql);
            ResultSet rs=statement.executeQuery();
            if(rs.next()){
                 sumOfNetPay=rs.getInt(1);
           
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
          try {
            String sql="select SUM(net_payable) from sallery where r_shift='"+runningShift+"' and "
                    + "r_department  between '"+departmentFrom+"'"
                    + " and '"+departmentTo+"' and pending_status='1'"
                    + " and week_end_date='"+toDate+"'";
            PreparedStatement statement=connection.prepareStatement(sql);
            ResultSet rs=statement.executeQuery();
            if(rs.next()){
                 sumOfPending=rs.getInt(1);
               
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        totalInNumber=sumOfNetPay-sumOfPending;
        System.err.println(sumOfNetPay+"\t"+sumOfPending+"\t"+totalInNumber);
        
        
        totalInWords="Total Tk.("+DigitsToWords.convert(totalInNumber)+" )Only";
        System.err.println(totalInWords);
        
        
        
           }

    private void getParam_2() {
        
            parameter = new HashMap();
            parameter.put("ewwkEndDate", toDate);
           
            }

    private void getParam_3() {
        parameter = new HashMap();
        parameter.put("cardNo", cardNo);
        parameter.put("start_date", fromDate);
        parameter.put("end_date", toDate);
           }

    private void recordInquery() {
         cardNo = cardNoTF.getText();
                getMainFilePath();
        //getData();
        //getTotalInWords();
        getRunningDate();
        getParam_3();
        
       
        reportPanel.removeAll();
        reportPanel.repaint();
        reportPanel.revalidate();       
     
        try {
             JasperDesign jDesign = JRXmlLoader.load(parent+"\\src\\demo_wages\\report\\attendence_inquery.jrxml");
                        JasperReport jReport = JasperCompileManager.compileReport(jDesign);
                        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, connection);
                        JRViewer jRViewer = new JRViewer(jPrint);
                        reportPanel.setLayout(new BorderLayout());
                        reportPanel.add(jRViewer);
        } catch (Exception e) {
            e.printStackTrace();
        }
            }

}
