/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_wages;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MJIL
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public static Connection connection;
    private String name;
    private String fatherName;
    private String department;
    private String designation;
    private String payableCode;
    private Date joinningDate;
    private Date desertionDate;
    private String address;
    private String gender;
    private String employeeType;
    private int relieverStatus;
    private String activeStatus;
    private String relieverType;
    private int wagesRate;
    private String saleryType;
    private int relieverAllowance;
    private int specialAllowance;
    private int extraAllowance;
    private String phone;
    private String errorMessege;
    private int tokenNo;
    private int otRate;

    public Employee() {
        initComponents();
        connection = DBconnect.dbconnect();
        payable_code_combo.setSelectedItem("C");
        showEmployeeTable();
        departmentItem();
        designationItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        reliever_group = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        reliever_allo_lbl = new javax.swing.JLabel();
        reliever_allo_tf = new javax.swing.JTextField();
        reliever_chbox = new javax.swing.JCheckBox();
        sr_reliever_rb = new javax.swing.JRadioButton();
        reliever_rb = new javax.swing.JRadioButton();
        reliever_tk_lbl = new javax.swing.JLabel();
        jr_reliever_rb = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        special_allow_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        extra_allowance_tf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        otRateTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        wagesRateTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        department_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        designation_combo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        employee_type_combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        payable_code_combo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        token_no_tf = new javax.swing.JTextField();
        btn_search = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        extra_token_no_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fathers_name_tf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        address_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        active_status_combo = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        key_tf = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        joining_date_dc = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        desertion_date_dc = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        btn_add_employee = new javax.swing.JButton();
        btn_update_employee = new javax.swing.JButton();
        btn_delete_employee = new javax.swing.JButton();
        btn_clear_fields = new javax.swing.JButton();
        error_message_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(950, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 615));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        reliever_allo_lbl.setText("Reliever Allowance");
        reliever_allo_lbl.setEnabled(false);

        reliever_allo_tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        reliever_allo_tf.setEnabled(false);
        reliever_allo_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reliever_allo_tfKeyReleased(evt);
            }
        });

        reliever_chbox.setText("Reliever");
        reliever_chbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reliever_chboxActionPerformed(evt);
            }
        });

        reliever_group.add(sr_reliever_rb);
        sr_reliever_rb.setText("Sr. Reliever");
        sr_reliever_rb.setEnabled(false);
        sr_reliever_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_reliever_rbActionPerformed(evt);
            }
        });

        reliever_group.add(reliever_rb);
        reliever_rb.setText("Reliever");
        reliever_rb.setEnabled(false);

        reliever_tk_lbl.setText("Tk/Day");
        reliever_tk_lbl.setEnabled(false);

        reliever_group.add(jr_reliever_rb);
        jr_reliever_rb.setText("Jr. Reliever");
        jr_reliever_rb.setEnabled(false);

        jLabel10.setText("Spec. Allow.");

        special_allow_tf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        special_allow_tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        special_allow_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                special_allow_tfKeyReleased(evt);
            }
        });

        jLabel11.setText("Tk/Day");

        jLabel13.setText("Extra Allow.");

        extra_allowance_tf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        extra_allowance_tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setText("Shift");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "A", "B", "C" }));

        jLabel18.setText("OT Rate");

        otRateTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        otRateTF.setForeground(java.awt.Color.red);

        jLabel24.setText("Tk/Day");

        jLabel25.setText("Wages Rate");

        wagesRateTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        wagesRateTF.setForeground(java.awt.Color.red);

        jLabel26.setText("Tk/Day");

        jLabel27.setText("Tk/Day");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reliever_allo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reliever_allo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reliever_tk_lbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(reliever_chbox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(sr_reliever_rb)
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(reliever_rb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jr_reliever_rb))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(special_allow_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(wagesRateTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(otRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(extra_allowance_tf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addGap(6, 6, 6))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(otRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(wagesRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(extra_allowance_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(special_allow_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reliever_chbox)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr_reliever_rb)
                    .addComponent(reliever_rb)
                    .addComponent(jr_reliever_rb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reliever_allo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reliever_allo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reliever_tk_lbl))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel6.setText("Department");

        department_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));

        jLabel7.setText("Designation");

        designation_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));
        designation_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designation_comboActionPerformed(evt);
            }
        });

        jLabel12.setText("Employee Type");

        employee_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Permanent", "Temporary" }));
        employee_type_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_type_comboActionPerformed(evt);
            }
        });

        jLabel9.setText("Payable Code");

        payable_code_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "G", "C" }));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Plus_20px_1.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Plus_20px_1.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(employee_type_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(payable_code_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(department_combo, 0, 114, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(designation_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(department_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(designation_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payable_code_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel3.setText("ID/Token Number");

        token_no_tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        token_no_tf.setForeground(new java.awt.Color(204, 0, 0));
        token_no_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                token_no_tfActionPerformed(evt);
            }
        });

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_20px.png"))); // NOI18N
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Extra Token Number");

        extra_token_no_tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setText("Name");

        jLabel14.setText("Fathers Name");

        jLabel15.setText("Address");

        jLabel2.setText("Gender");

        gender_group.add(male_radio);
        male_radio.setText("Male");

        gender_group.add(female_radio);
        female_radio.setText("Female");

        jLabel20.setText("Active Status");

        active_status_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Active", "Inactive" }));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/photo.png"))); // NOI18N

        jButton1.setText("Upload Photo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(token_no_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extra_token_no_tf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(male_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(female_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(active_status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name_tf))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fathers_name_tf))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(address_tf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(token_no_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(extra_token_no_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fathers_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(male_radio)
                            .addComponent(female_radio)
                            .addComponent(active_status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        employee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        employee_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employee_table);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("All Employee");

        key_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key_tfActionPerformed(evt);
            }
        });

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_16px.png"))); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(key_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(key_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel19.setText("Joining Date");

        joining_date_dc.setDateFormatString("MMddyyyy");

        jLabel21.setText("Date of Desertion");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joining_date_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(desertion_date_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desertion_date_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joining_date_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        btn_add_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Plus_20px_1.png"))); // NOI18N
        btn_add_employee.setText("Add");
        btn_add_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_employeeActionPerformed(evt);
            }
        });

        btn_update_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Update_20px.png"))); // NOI18N
        btn_update_employee.setText("Update");
        btn_update_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_employeeActionPerformed(evt);
            }
        });

        btn_delete_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_Database_20px.png"))); // NOI18N
        btn_delete_employee.setText("Delete");

        btn_clear_fields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_20px.png"))); // NOI18N
        btn_clear_fields.setText("Clear");
        btn_clear_fields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_fieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btn_add_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_clear_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_employee)
                    .addComponent(btn_update_employee)
                    .addComponent(btn_delete_employee)
                    .addComponent(btn_clear_fields))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        error_message_lbl.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error_message_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_message_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clear_fieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_fieldsActionPerformed
        // TODO add your handling code here:
        initFields();
    }//GEN-LAST:event_btn_clear_fieldsActionPerformed

    private void btn_update_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_employeeActionPerformed
        // TODO add your handling code here:
        updateEmployee();
    }//GEN-LAST:event_btn_update_employeeActionPerformed

    private void btn_add_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_employeeActionPerformed
        // TODO add your handling code here:
        addEmployee();
    }//GEN-LAST:event_btn_add_employeeActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String key = key_tf.getText();

        if (!key.isEmpty()) {
            try {
                String sql_1 = "select card_no,name,department from employee where name like '%" + key + "%' or department like '%" + key + "%'"
                + "or card_no like '%" + key + "%'";
                PreparedStatement st = connection.prepareStatement(sql_1);
                ResultSet rs_1 = st.executeQuery();
                employee_table.setModel(DbUtils.resultSetToTableModel(rs_1));

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } else {
            showEmployeeTable();
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void key_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key_tfActionPerformed
        // TODO add your handling code here:
        String key = key_tf.getText();

        if (!key.isEmpty()) {
            try {
                String sql_1 = "select card_no,name,department from employee where name like '%" + key + "%' or department like '%" + key + "%'"
                + "or card_no like '%" + key + "%'";
                PreparedStatement st = connection.prepareStatement(sql_1);
                ResultSet rs_1 = st.executeQuery();
                employee_table.setModel(DbUtils.resultSetToTableModel(rs_1));

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } else {
            showEmployeeTable();
        }
    }//GEN-LAST:event_key_tfActionPerformed

    private void employee_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_tableMouseClicked
        // TODO add your handling code here:
        settSelectedData();
    }//GEN-LAST:event_employee_tableMouseClicked

    private void employee_type_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_type_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_type_comboActionPerformed

    private void sr_reliever_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_reliever_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr_reliever_rbActionPerformed

    private void reliever_chboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reliever_chboxActionPerformed
        // TODO add your handling code here:
        if (reliever_chbox.isSelected()) {
            reliever_allo_lbl.setEnabled(true);
            sr_reliever_rb.setEnabled(true);
            reliever_rb.setEnabled(true);
            jr_reliever_rb.setEnabled(true);
            reliever_allo_tf.setEnabled(true);
            reliever_tk_lbl.setEnabled(true);
        } else {
            reliever_allo_lbl.setEnabled(false);
            sr_reliever_rb.setEnabled(false);
            reliever_rb.setEnabled(false);
            jr_reliever_rb.setEnabled(false);
            reliever_allo_tf.setEnabled(false);
            reliever_tk_lbl.setEnabled(false);
        }
    }//GEN-LAST:event_reliever_chboxActionPerformed

    private void token_no_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_token_no_tfActionPerformed
        // TODO add your handling code here:
        String key=token_no_tf.getText();
        if(!key.equals("")){
            setSelectedDataByUser(key);
            designation_combo.requestFocus();
        }
        
    }//GEN-LAST:event_token_no_tfActionPerformed

    private void designation_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designation_comboActionPerformed
        // TODO add your handling code here:
        if(wagesRate<=0){
            try {
            String sql="select wages_rate from wages_mangement where department="
                    + "'"+department_combo.getSelectedItem()+"' "
                    + "and designation='"+designation_combo.getSelectedItem()+"'";
            PreparedStatement statement=connection.prepareStatement(sql);
            ResultSet rs=statement.executeQuery();
            if(rs.next()){
                wagesRateTF.setText(String.valueOf(rs.getInt("wages_rate")));
                otRateTF.setText(String.valueOf(rs.getInt("wages_rate")));
                otRate=rs.getInt("wages_rate");
               // joining_date_dc.requestFocus();
            }
           // joining_date_dc.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_designation_comboActionPerformed

    private void special_allow_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_special_allow_tfKeyReleased
        // TODO add your handling code here:
if(!special_allow_tf.getText().isEmpty()){
    specialAllowance=Integer.parseInt(special_allow_tf.getText());   
    
}else{
    specialAllowance=0;
}
otRateTF.setText(String.valueOf(otRate+specialAllowance+relieverAllowance));   
    }//GEN-LAST:event_special_allow_tfKeyReleased

    private void reliever_allo_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reliever_allo_tfKeyReleased
        // TODO add your handling code here:
        
    if(!reliever_allo_tf.getText().isEmpty()){
    relieverAllowance=Integer.parseInt(reliever_allo_tf.getText());   
    
}else{
    relieverAllowance=0;
}
otRateTF.setText(String.valueOf(otRate+specialAllowance+relieverAllowance));   
    }//GEN-LAST:event_reliever_allo_tfKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Employee().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> active_status_combo;
    private javax.swing.JTextField address_tf;
    private javax.swing.JButton btn_add_employee;
    private javax.swing.JButton btn_clear_fields;
    private javax.swing.JButton btn_delete_employee;
    private javax.swing.JLabel btn_search;
    private javax.swing.JButton btn_update_employee;
    private javax.swing.JComboBox<String> department_combo;
    private com.toedter.calendar.JDateChooser desertion_date_dc;
    private javax.swing.JComboBox<String> designation_combo;
    private javax.swing.JTable employee_table;
    private javax.swing.JComboBox<String> employee_type_combo;
    private javax.swing.JLabel error_message_lbl;
    private javax.swing.JTextField extra_allowance_tf;
    private javax.swing.JTextField extra_token_no_tf;
    private javax.swing.JTextField fathers_name_tf;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser joining_date_dc;
    private javax.swing.JRadioButton jr_reliever_rb;
    private javax.swing.JTextField key_tf;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField name_tf;
    private javax.swing.JTextField otRateTF;
    private javax.swing.JComboBox<String> payable_code_combo;
    private javax.swing.JLabel reliever_allo_lbl;
    private javax.swing.JTextField reliever_allo_tf;
    private javax.swing.JCheckBox reliever_chbox;
    private javax.swing.ButtonGroup reliever_group;
    private javax.swing.JRadioButton reliever_rb;
    private javax.swing.JLabel reliever_tk_lbl;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField special_allow_tf;
    private javax.swing.JRadioButton sr_reliever_rb;
    private javax.swing.JTextField token_no_tf;
    private javax.swing.JTextField wagesRateTF;
    // End of variables declaration//GEN-END:variables

    private void showEmployeeTable() {

        try {
            String sql_1 = "select card_no,name,department from employee ORDER BY department";
            PreparedStatement st = connection.prepareStatement(sql_1);
            ResultSet rs_1 = st.executeQuery();
            employee_table.setModel(DbUtils.resultSetToTableModel(rs_1));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    private void departmentItem() {

        try {

            String sql_1 = "select * from department";
            PreparedStatement st = connection.prepareStatement(sql_1);
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                department_combo.addItem(rs.getString("department_name"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void designationItem() {

        try {

            String sql_1 = "select DISTINCT designation from wages_mangement";
            PreparedStatement st = connection.prepareStatement(sql_1);
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                designation_combo.addItem(rs.getString("designation"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void settSelectedData() {

        int row = employee_table.getSelectedRow();
        String tableClicked = (employee_table.getModel().getValueAt(row, 0).toString());

        setSelectedDataByUser(tableClicked);

    }

    private void initFields() {
        token_no_tf.setText("");
        extra_token_no_tf.setText("");
        name_tf.setText("");
        fathers_name_tf.setText("");
        address_tf.setText("");
        active_status_combo.setSelectedItem("Select One");
        department_combo.setSelectedItem("Select One");
        designation_combo.setSelectedItem("Select One");
        employee_type_combo.setSelectedItem("Select One");
        payable_code_combo.setSelectedItem("C");
        special_allow_tf.setText("");
        extra_allowance_tf.setText("");
        reliever_chbox.setSelected(false);
        reliever_allo_tf.setText("");
        joining_date_dc.setCalendar(null);
        desertion_date_dc.setCalendar(null);
        otRateTF.setText("");
        wagesRateTF.setText("");

        name = "";
        fatherName = "";
        department = "";
        designation = "";
        payableCode = "";
        joinningDate = null;
        desertionDate = null;
        address = "";
        gender = "";
        employeeType = "";
        relieverStatus = 0;
        activeStatus = "";
        relieverType = "";
        wagesRate = 0;
        saleryType = "";
        relieverAllowance = 0;
        specialAllowance = 0;
        extraAllowance = 0;
        phone = "";
        errorMessege = "";
        tokenNo = 0;
        otRate=0;

    }

    private void getData() {
        error_message_lbl.setText("");
        errorMessege = "Followuing fields are required...";
        try {
            tokenNo = Integer.parseInt(token_no_tf.getText());

        } catch (NumberFormatException e) {
            errorMessege += " token number.";
            error_message_lbl.setText(errorMessege);
        }
        name = name_tf.getText();
        if (name.isEmpty()) {
            errorMessege += " name.";
            error_message_lbl.setText(errorMessege);
        }
        fatherName = fathers_name_tf.getText();
        department = department_combo.getSelectedItem().toString();
        if (department.equals("Select One")) {
            errorMessege += " department.";
            error_message_lbl.setText(errorMessege);
        }

        designation = designation_combo.getSelectedItem().toString();
        if (designation.equals("Select One")) {
            errorMessege += " designation.";
            error_message_lbl.setText(errorMessege);
        }
        payableCode = payable_code_combo.getSelectedItem().toString();
        if (payableCode.equals("Select One")) {
            errorMessege += " payable code.";
            error_message_lbl.setText(errorMessege);
        }
        joinningDate = joining_date_dc.getDate();
        if (joinningDate == null) {
            errorMessege += ""
                    + " joinning date.";
            error_message_lbl.setText(errorMessege);
        }

        desertionDate = desertion_date_dc.getDate();
        address = address_tf.getText();

        if (male_radio.isSelected()) {
            gender = male_radio.getText();
        } else if (female_radio.isSelected()) {
            gender = female_radio.getText();
        }
        employeeType = employee_type_combo.getSelectedItem().toString();
        activeStatus = active_status_combo.getSelectedItem().toString();

        wagesRate =Integer.parseInt(wagesRateTF.getText());
        saleryType = "";
        if (reliever_chbox.isSelected()) {
            try {
                relieverAllowance = Integer.parseInt(reliever_allo_tf.getText());
            } catch (NumberFormatException e) {
                //JOptionPane.showMessageDialog(this, "Reliever allowance is not valid.");
                errorMessege += " Reliever allowance.";
                error_message_lbl.setText(errorMessege);
            }
            relieverStatus = 1;
            if (reliever_rb.isSelected()) {
                relieverType = reliever_rb.getText();
            } else if (sr_reliever_rb.isSelected()) {
                relieverType = sr_reliever_rb.getText();
            } else if (jr_reliever_rb.isSelected()) {
                relieverType = jr_reliever_rb.getText();
            }
            if (relieverType == null || relieverType.isEmpty()) {
                errorMessege += " Reliever type.";
                error_message_lbl.setText(errorMessege);
            }
        }
        if (!special_allow_tf.getText().isEmpty()) {
            try {
                specialAllowance = Integer.parseInt(special_allow_tf.getText());
            } catch (NumberFormatException e) {
                // JOptionPane.showMessageDialog(this, "Special allowance is not valid.");
                errorMessege += " Special allowance.";
                error_message_lbl.setText(errorMessege);

            }
        }
        
        
            if (!otRateTF.getText().isEmpty()) {
            try {
                otRate = Integer.parseInt(otRateTF.getText());
            } catch (NumberFormatException e) {
                // JOptionPane.showMessageDialog(this, "Special allowance is not valid.");
                errorMessege += " OT Rate.";
                error_message_lbl.setText(errorMessege);
            }
        }else{
                errorMessege += " OT Rate.";
                error_message_lbl.setText(errorMessege);
            }

        if (!extra_allowance_tf.getText().isEmpty()) {
            try {
                extraAllowance = Integer.parseInt(extra_allowance_tf.getText());
            } catch (NumberFormatException e) {
                //JOptionPane.showMessageDialog(this, "Extra allowance is not valid.");
                errorMessege += " Extra allowance.";
                error_message_lbl.setText(errorMessege);
                return;
            }
        }
        phone = "";
    }

    private void addEmployee() {
        getData();
        java.sql.Date sqlJoinDate = null, sqlDesertionDate = null;
        if (joinningDate != null) {
            sqlJoinDate = new java.sql.Date(joinningDate.getTime());
        }
        if (desertionDate != null) {
            sqlDesertionDate = new java.sql.Date(desertionDate.getTime());
        }

        if (error_message_lbl.getText().isEmpty()) {

            try {
                String sql = "select * from employee where card_no='" + tokenNo + "'";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Duplicate Entry.");
                } else {
                    String sql_1 = "insert into employee"
                            + "(card_no,name,father_name,department,designation,pay_able_code,joining_date,"
                            + "date_of_desertion,address,gender,employee_type,reliever_status,"
                            + "active_status,reliever_type,wages_rate,"
                            + "sallery_type,reliever_allowance,special_allowance,extra_allowance,phone,ot_rate)"
                            + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    try (PreparedStatement statement = connection.prepareStatement(sql_1)) {
                        statement.setInt(1, tokenNo);
                        statement.setString(2, name);
                        statement.setString(3, fatherName);
                        statement.setString(4, department);
                        statement.setString(5, designation);
                        statement.setString(6, payableCode);
                        statement.setDate(7, sqlJoinDate);
                        statement.setDate(8, sqlDesertionDate);
                        statement.setString(9, address);
                        statement.setString(10, gender);
                        statement.setString(11, employeeType);
                        statement.setInt(12, relieverStatus);
                        statement.setString(13, activeStatus);
                        statement.setString(14, relieverType);
                        statement.setInt(15, wagesRate);
                        statement.setString(16, saleryType);
                        statement.setInt(17, relieverAllowance);
                        statement.setInt(18, specialAllowance);
                        statement.setInt(19, extraAllowance);
                        statement.setString(20, phone);
                        statement.setInt(21, otRate);
                        statement.executeUpdate();
                    }

                    showEmployeeTable();
                    initFields();
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Error!!! Process Failed.");
            }

        }

    }

    private void updateEmployee() {

        getData();
        java.sql.Date sqlJoinDate = null, sqlDesertionDate = null;
        if (joinningDate != null) {
            sqlJoinDate = new java.sql.Date(joinningDate.getTime());
        }
        if (desertionDate != null) {
            sqlDesertionDate = new java.sql.Date(desertionDate.getTime());
        }

        if (error_message_lbl.getText().isEmpty()) {

            try {
                String sql = "select * from employee where card_no='" + tokenNo + "'";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if (rs.next()) {

                    String sql_2 = "update employee set name = '" + name + "',"
                            + "father_name = '" + fatherName + "',"
                            + "department = '" + department + "',"
                            + "designation = '" + designation + "',"
                            + "pay_able_code = '" + payableCode + "',"
                            + "joining_date = '" + sqlJoinDate + "',"
                            + "address = '" + address + "',"
                            + "gender = '" + gender + "',"
                            + "employee_type = '" + employeeType + "',"
                            + "reliever_status = '" + relieverStatus + "',"
                            + "active_status = '" + activeStatus + "',"
                            + "reliever_type = '" + relieverType + "',"
                            + "wages_rate = '" + wagesRate + "',"
                            + "sallery_type = '" + saleryType + "',"
                            + "reliever_allowance = '" + relieverAllowance + "',"
                            + "special_allowance = '" + specialAllowance + "',"
                            + "extra_allowance = '" + extraAllowance + "',"
                            + "phone = '" + phone + "',"
                            + "ot_rate = '" + otRate + "'"
                            + " where card_no='" + tokenNo + "'";
                    PreparedStatement statement = connection.prepareStatement(sql_2);
                    statement.executeUpdate();
                    initFields();
                    token_no_tf.requestFocus();

                    if (sqlDesertionDate != null) {
                        String sql_3 = "update employee set date_of_desertion = '" + sqlDesertionDate + "'"
                                + " where card_no='" + tokenNo + "'";
                        PreparedStatement statement_2 = connection.prepareStatement(sql_3);
                        statement_2.executeUpdate();
                        initFields();
                        token_no_tf.requestFocus();
                    }

                   // JOptionPane.showMessageDialog(this, "Update record successful.");

                    showEmployeeTable();
                    // initFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Employee not found to update.");

                }
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
            }
        }
    }



    private void setSelectedDataByUser(String cardNumber) {
        
                try {

            String sql = "select * from employee where card_no='" + cardNumber + "'";
            PreparedStatement st = connection.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                token_no_tf.setText(String.valueOf(rs.getInt("card_no")));
                name_tf.setText(rs.getString("name"));
                fathers_name_tf.setText(rs.getString("father_name"));
                address_tf.setText(rs.getString("address"));
                wagesRate=rs.getInt("wages_rate");
                wagesRateTF.setText(String.valueOf(rs.getInt("wages_rate")));
                special_allow_tf.setText(String.valueOf(rs.getInt("special_allowance")));
                int releiverStatus = rs.getInt("reliever_status");
                if (releiverStatus == 1) {
                    reliever_chbox.setSelected(true);
                    reliever_allo_lbl.setEnabled(true);
                    sr_reliever_rb.setEnabled(true);
                    reliever_rb.setEnabled(true);
                    jr_reliever_rb.setEnabled(true);
                    reliever_allo_tf.setEnabled(true);
                    reliever_tk_lbl.setEnabled(true);
                } else {
                    reliever_chbox.setSelected(false);
                    reliever_allo_lbl.setEnabled(false);
                    sr_reliever_rb.setEnabled(false);
                    reliever_rb.setEnabled(false);
                    jr_reliever_rb.setEnabled(false);
                    reliever_allo_tf.setEnabled(false);
                    reliever_tk_lbl.setEnabled(false);
                }

                String nDepartment = rs.getString("department");
                if (!nDepartment.isEmpty()) {
                    department_combo.setSelectedItem(nDepartment);
                } else {
                    department_combo.setSelectedItem("Select One");
                }

                String nDesignation = rs.getString("designation");
                if (!nDesignation.isEmpty()) {
                    designation_combo.setSelectedItem(nDesignation);
                } else {
                    designation_combo.setSelectedItem("Select One");
                }

                String nEmployeeType = rs.getString("employee_type");
                if (nEmployeeType != null) {
                    employee_type_combo.setSelectedItem(nEmployeeType);
                } else {
                    employee_type_combo.setSelectedItem("Select One");
                }

                String nPayableCode = rs.getString("pay_able_code");
                if (nPayableCode != null) {
                    payable_code_combo.setSelectedItem(nPayableCode);
                } else {
                    payable_code_combo.setSelectedItem("Select One");
                }

                String nGender = rs.getString("gender");

                if (nGender.equals("Male") || nGender.equals("male")) {
                    male_radio.setSelected(true);
                } else if (nGender.equals("Female") || nGender.equals("female")) {
                    female_radio.setSelected(true);
                }

                String nRelieverType = rs.getString("reliever_type");
                if (nRelieverType != null && nRelieverType.equals("Sr. Reliever")) {
                    sr_reliever_rb.setSelected(true);
                } else if (nRelieverType != null && nRelieverType.equals("Reliever")) {
                    reliever_rb.setSelected(true);
                } else if (nRelieverType != null && nRelieverType.equals("Jr. Reliever")) {
                    jr_reliever_rb.setSelected(true);
                }
                reliever_allo_tf.setText(String.valueOf(rs.getInt("reliever_allowance")));

                java.sql.Date nJoinningDate = rs.getDate("joining_date");
                if (nJoinningDate != null) {
                    joining_date_dc.setDate(nJoinningDate);
                } else {
                    joining_date_dc.setCalendar(null);
                }
                java.sql.Date desrtionDate = rs.getDate("date_of_desertion");
                if (desrtionDate != null) {
                    desertion_date_dc.setDate(desrtionDate);
                } else {
                    desertion_date_dc.setCalendar(null);
                }
                String active_status = rs.getString("active_status");
                if (active_status != null) {
                    active_status_combo.setSelectedItem(active_status);
                } else {
                    active_status_combo.setSelectedItem("Select One");
                }
                extra_allowance_tf.setText(String.valueOf(rs.getInt("extra_allowance")));
                otRateTF.setText(String.valueOf(rs.getInt("ot_rate")));

                st.close();
                rs.close();
            } else {
                JOptionPane.showMessageDialog(this, "Employee not found.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
            }

}
