/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_wages;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MJIL
 */
public class PendingWagesTokenEntry extends javax.swing.JFrame {

    /**
     * Creates new form BlockWagesTokenEntry
     */
    public static Connection connection;
    private Date weekStartDate;
    private Date weekEndDate;
    private int millRunningHour;
    private int millHollyDayahour;
    private int cardNo;
    private String department;
    private String shift;
    private int workHour;
    private int wagesRate;
    private int billAmount;
    private int otHours;
    private int otWages;
    private String empName;

    public PendingWagesTokenEntry() {
        initComponents();
        connection = DBconnect.dbconnect();
    getRunningWeek();
        getAllWeeks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        weekStatrtDateTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        weekEndDateTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        millRuningHourTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        millHollyDayHourTF = new javax.swing.JTextField();
        weekEndDateCombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardNoTF = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        oriDeptTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        runingDeptTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        oriShiftTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        runingShiftTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        designationTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        wagesRateTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        otRateTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        releAllowTF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        specialAllowTF = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        attendanceTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        otTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        hollyDayHourTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fesTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        subTotalTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        otWagesTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        hollyDayAllowTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        attnAllowTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nightAlloeTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        deductionTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        netPayTF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        jLabel39.setText("TK");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pending Wages Token Entry");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("Week Start Date");

        weekStatrtDateTF.setEditable(false);

        jLabel4.setText("Week End Date");

        weekEndDateTF.setEditable(false);

        jLabel11.setText("Mill Runing Hour");

        millRuningHourTF.setEditable(false);
        millRuningHourTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel16.setText("Mill Holly day Hour");

        millHollyDayHourTF.setEditable(false);
        millHollyDayHourTF.setBackground(java.awt.SystemColor.controlHighlight);

        weekEndDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select week End Date" }));

        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weekEndDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weekStatrtDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weekEndDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(millHollyDayHourTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(millRuningHourTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(weekStatrtDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(weekEndDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(millRuningHourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(millHollyDayHourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(weekEndDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel2.setText("Card No.");

        cardNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNoTFActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_16px.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        nameTF.setEditable(false);
        nameTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel6.setText("Ori. Dept");

        oriDeptTF.setEditable(false);
        oriDeptTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel7.setText("Runing Dept");

        runingDeptTF.setEditable(false);
        runingDeptTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel8.setText("Ori. Shift");

        oriShiftTF.setEditable(false);
        oriShiftTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel9.setText("Runing Shift");

        runingShiftTF.setEditable(false);
        runingShiftTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel10.setText("Desination");

        designationTF.setEditable(false);
        designationTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel24.setText("Wages Rate");

        wagesRateTF.setEditable(false);
        wagesRateTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel25.setText("OT Rate");

        otRateTF.setEditable(false);
        otRateTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel26.setText("Rellever Allow.");

        releAllowTF.setEditable(false);
        releAllowTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel27.setText("TK/Day");

        jLabel28.setText("TK/Day");

        jLabel41.setText("TK/Day");

        jLabel42.setText("Special Allow.");

        specialAllowTF.setEditable(false);
        specialAllowTF.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel43.setText("TK/Day");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTF)
                            .addComponent(oriDeptTF)
                            .addComponent(runingDeptTF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(oriShiftTF))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(designationTF)
                                    .addComponent(runingShiftTF)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(specialAllowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel43))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(otRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel28))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(wagesRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel27))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(releAllowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel41)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(oriDeptTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(runingDeptTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(oriShiftTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(runingShiftTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(designationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(wagesRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(otRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(releAllowTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(specialAllowTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addContainerGap())
        );

        jLabel12.setText("Attendence(Hours)");

        attendanceTF.setEditable(false);
        attendanceTF.setBackground(java.awt.SystemColor.controlHighlight);
        attendanceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceTFActionPerformed(evt);
            }
        });

        jLabel13.setText("OT Hours");

        otTF.setEditable(false);
        otTF.setBackground(java.awt.SystemColor.controlHighlight);
        otTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otTFActionPerformed(evt);
            }
        });

        jLabel14.setText("Holly day Hour");

        hollyDayHourTF.setEditable(false);
        hollyDayHourTF.setBackground(java.awt.SystemColor.controlHighlight);
        hollyDayHourTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hollyDayHourTFActionPerformed(evt);
            }
        });

        jLabel15.setText("Festival Allow");

        fesTF.setEditable(false);
        fesTF.setBackground(java.awt.SystemColor.controlHighlight);
        fesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fesTFActionPerformed(evt);
            }
        });

        jLabel17.setText("Sub Total");

        subTotalTF.setEditable(false);
        subTotalTF.setBackground(java.awt.SystemColor.controlHighlight);
        subTotalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalTFActionPerformed(evt);
            }
        });

        jLabel18.setText("OT Wages");

        otWagesTF.setEditable(false);
        otWagesTF.setBackground(java.awt.SystemColor.controlHighlight);
        otWagesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otWagesTFActionPerformed(evt);
            }
        });

        jLabel19.setText("Holly day Allow");

        hollyDayAllowTF.setEditable(false);
        hollyDayAllowTF.setBackground(java.awt.SystemColor.controlHighlight);
        hollyDayAllowTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hollyDayAllowTFActionPerformed(evt);
            }
        });

        jLabel20.setText("Attn. Allow.");

        attnAllowTF.setEditable(false);
        attnAllowTF.setBackground(java.awt.SystemColor.controlHighlight);
        attnAllowTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attnAllowTFActionPerformed(evt);
            }
        });

        jLabel21.setText("Night Allow.");

        nightAlloeTF.setEditable(false);
        nightAlloeTF.setBackground(java.awt.SystemColor.controlHighlight);
        nightAlloeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightAlloeTFActionPerformed(evt);
            }
        });

        jLabel22.setText("Deduction");

        deductionTF.setEditable(false);
        deductionTF.setBackground(java.awt.SystemColor.controlHighlight);
        deductionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductionTFActionPerformed(evt);
            }
        });

        jLabel23.setText("Net Payable");

        netPayTF.setEditable(false);
        netPayTF.setBackground(java.awt.SystemColor.controlHighlight);
        netPayTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netPayTFActionPerformed(evt);
            }
        });

        jLabel29.setText("Hours");

        jLabel30.setText("Hours");

        jLabel31.setText("Hours");

        jLabel32.setText("TK");

        jLabel33.setText("TK");

        jLabel34.setText("TK");

        jLabel35.setText("TK");

        jLabel36.setText("TK");

        jLabel37.setText("TK");

        jLabel38.setText("TK");

        jLabel40.setText("TK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attendanceTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hollyDayHourTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fesTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(subTotalTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(otWagesTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hollyDayAllowTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(attnAllowTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel36)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(nightAlloeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel37)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(deductionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel38)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(netPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel40)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(otTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hollyDayHourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(otWagesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(hollyDayAllowTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(attnAllowTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nightAlloeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(deductionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(netPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(10, 10, 10))
        );

        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.setEnabled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear)
                    .addComponent(btnRemove))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String endDate = weekEndDateCombo.getSelectedItem().toString();
        if (endDate.equals("Select week End Date")) {
            JOptionPane.showMessageDialog(this, "Please select Week End Date.");
        } else {
            Date date = Date.valueOf(endDate);
            getSelectedWeek(date);
        }
        //clearFields();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void attendanceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_attendanceTFActionPerformed

    private void otTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_otTFActionPerformed

    private void hollyDayHourTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hollyDayHourTFActionPerformed

    }//GEN-LAST:event_hollyDayHourTFActionPerformed

    private void fesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fesTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fesTFActionPerformed

    private void subTotalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalTFActionPerformed

    private void otWagesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otWagesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otWagesTFActionPerformed

    private void hollyDayAllowTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hollyDayAllowTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hollyDayAllowTFActionPerformed

    private void attnAllowTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attnAllowTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attnAllowTFActionPerformed

    private void nightAlloeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightAlloeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightAlloeTFActionPerformed

    private void deductionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductionTFActionPerformed

    private void netPayTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netPayTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netPayTFActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:

        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void cardNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNoTFActionPerformed
        // TODO add your handling code here:
        String key = cardNoTF.getText();
        cardNo = Integer.parseInt(key);
        getData(key);
        if (pendingStatus(key)) {
            btnRemove.setEnabled(true);
            btnSave.setEnabled(false);
            btnRemove.requestFocus();
        } else {
            btnRemove.setEnabled(false);
            btnSave.setEnabled(true);
            btnSave.requestFocus();
        }

    }//GEN-LAST:event_cardNoTFActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (pendingStatus(String.valueOf(cardNo))) {
            JOptionPane.showMessageDialog(this, "Duplicate Entry.");
        } else {
            addToPending();
            clear();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String key = cardNoTF.getText();
        cardNo = Integer.parseInt(key);
        getData(key);
        if (pendingStatus(key)) {
            btnRemove.setEnabled(true);
            btnSave.setEnabled(false);
            btnRemove.requestFocus();
        } else {
            btnRemove.setEnabled(false);
            btnSave.setEnabled(true);
            btnSave.requestFocus();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        removeFromPending(cardNo);
        clear();
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingWagesTokenEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingWagesTokenEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingWagesTokenEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingWagesTokenEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PendingWagesTokenEntry().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attendanceTF;
    private javax.swing.JTextField attnAllowTF;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField cardNoTF;
    private javax.swing.JTextField deductionTF;
    private javax.swing.JTextField designationTF;
    private javax.swing.JTextField fesTF;
    private javax.swing.JTextField hollyDayAllowTF;
    private javax.swing.JTextField hollyDayHourTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField millHollyDayHourTF;
    private javax.swing.JTextField millRuningHourTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField netPayTF;
    private javax.swing.JTextField nightAlloeTF;
    private javax.swing.JTextField oriDeptTF;
    private javax.swing.JTextField oriShiftTF;
    private javax.swing.JTextField otRateTF;
    private javax.swing.JTextField otTF;
    private javax.swing.JTextField otWagesTF;
    private javax.swing.JTextField releAllowTF;
    private javax.swing.JTextField runingDeptTF;
    private javax.swing.JTextField runingShiftTF;
    private javax.swing.JTextField specialAllowTF;
    private javax.swing.JTextField subTotalTF;
    private javax.swing.JTextField wagesRateTF;
    private javax.swing.JComboBox<String> weekEndDateCombo;
    private javax.swing.JTextField weekEndDateTF;
    private javax.swing.JTextField weekStatrtDateTF;
    // End of variables declaration//GEN-END:variables

    private void getRunningWeek() {
        try {
            String sql = "select * from running_week";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                weekStartDate = rs.getDate("week_start_date");
                weekEndDate = rs.getDate("week_end_date");
                millRunningHour = rs.getInt("mill_running_hour");
                millHollyDayahour = rs.getInt("hollyday_hours");
                weekStatrtDateTF.setText(String.valueOf(weekStartDate));
                weekEndDateTF.setText(String.valueOf(weekEndDate));
                millRuningHourTF.setText(String.valueOf(millRunningHour));
                millHollyDayHourTF.setText(String.valueOf(millHollyDayahour));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void getAllWeeks() {
        try {
            String sql = "select * from week_setup order by week_end_date DESC limit 10";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                weekEndDateCombo.addItem(String.valueOf(rs.getDate("week_end_date")));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void getSelectedWeek(Date date) {
        try {
            String sql = "select * from week_setup where week_end_date='" + date + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                weekStartDate = rs.getDate("week_start_date");
                weekEndDate = rs.getDate("week_end_date");
                millRunningHour = rs.getInt("mill_running_hour");
                millHollyDayahour = rs.getInt("hollyday_hours");
                weekStatrtDateTF.setText(String.valueOf(weekStartDate));
                weekEndDateTF.setText(String.valueOf(weekEndDate));
                millRuningHourTF.setText(String.valueOf(millRunningHour));
                millHollyDayHourTF.setText(String.valueOf(millHollyDayahour));

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void getData(String key) {
        try {
            String sql = "select * from sallery where card_no='" + key + "' and week_start_date='" + weekStartDate + "'"
                    + " and week_end_date='" + weekEndDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                department = rs.getString("department");
                shift = rs.getString("r_shift");
                workHour = rs.getInt("working_hour");
                wagesRate = rs.getInt("daily_wages");
                billAmount = rs.getInt("net_payable");
                otHours = rs.getInt("ot_hour");
                otWages = (int) ((rs.getInt("ot_rate") / 8.0) * rs.getInt("ot_hour"));
                empName=rs.getString("name");

                
                nameTF.setText(empName);
                oriDeptTF.setText(department);
                runingDeptTF.setText(rs.getString("r_department"));
                runingShiftTF.setText(shift);
                designationTF.setText(rs.getString("designation"));
                wagesRateTF.setText(String.valueOf(wagesRate));
                otRateTF.setText(String.valueOf(rs.getInt("ot_rate")));
                releAllowTF.setText(String.valueOf(rs.getInt("reli_allo")));
                specialAllowTF.setText(String.valueOf(rs.getInt("special_allo")));
                attendanceTF.setText(String.valueOf(workHour));
                otTF.setText(String.valueOf(otHours));
                hollyDayHourTF.setText(String.valueOf(rs.getInt("hollyDayHour")));
                fesTF.setText(String.valueOf(rs.getInt("fes_allow")));
                subTotalTF.setText(String.valueOf(rs.getDouble("subtotal")));
                otWagesTF.setText(String.valueOf(otWages));
                hollyDayAllowTF.setText(String.valueOf(rs.getInt("hollyDayAllow")));
                attnAllowTF.setText(String.valueOf(rs.getInt("attn_allow")));
                nightAlloeTF.setText(String.valueOf(rs.getInt("night_allow")));
                deductionTF.setText(String.valueOf(rs.getInt("deduct")));
                netPayTF.setText(String.valueOf(billAmount));

            } else {
                JOptionPane.showMessageDialog(this, "No records found.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void addToPending() {
        try {
            String sql = "insert into pending (card_no,endofweek,department,shift,wo_hrs,wages_rate,bill_amount,"
                    + "paid_amount,paid_date,ot_hrs,ot_wages,paid_status,name) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setInt(1, cardNo);
            statement.setDate(2, weekEndDate);
            statement.setString(3, department);
            statement.setString(4, shift);
            statement.setInt(5, workHour);
            statement.setInt(6, wagesRate);
            statement.setInt(7, billAmount);
            statement.setInt(8, 0);
            statement.setDate(9, null);
            statement.setInt(10, otHours);
            statement.setInt(11, otWages);
            statement.setString(12, "Pending");
            statement.setString(13, empName);
            statement.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }

        try {
            String sql = "update sallery set pending_status='1' where card_no='" + cardNo + "' "
                    + "and week_start_date='" + weekStartDate + "' and week_end_date='" + weekEndDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private boolean pendingStatus(String key) {
        try {
            String sql = "select * from pending where card_no='" + key + "' and endofweek='" + weekEndDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            return rs.next();
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    private void removeFromPending(int cardNo) {
        try {
            String sql = "delete from pending where card_no='" + cardNo + "' and  endofweek='" + weekEndDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            String sql = "update sallery set pending_status='0' where card_no='" + cardNo + "' "
                    + "and week_start_date='" + weekStartDate + "' and week_end_date='" + weekEndDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clear() {
        nameTF.setText("");
        oriDeptTF.setText("");
        runingDeptTF.setText("");
        runingShiftTF.setText("");
        designationTF.setText("");
        wagesRateTF.setText(String.valueOf(""));
        otRateTF.setText("");
        releAllowTF.setText("");
        specialAllowTF.setText("");
        attendanceTF.setText("");
        otTF.setText("");
        hollyDayHourTF.setText("");
        fesTF.setText("");
        subTotalTF.setText("");
        otWagesTF.setText("");
        hollyDayAllowTF.setText("");
        attnAllowTF.setText("");
        nightAlloeTF.setText("");
        deductionTF.setText("");
        netPayTF.setText("");
        cardNoTF.setText("");

        cardNo = 0;
        department = "";
        shift = "";
        workHour = 0;
        wagesRate = 0;
        billAmount = 0;
        otHours = 0;
        otWages = 0;

    }
}
