/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_wages;

import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author MadinaJute
 */
public class ShiftRangeReport extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    private String parent = "";
    private HashMap parameter;
    private static Connection connection;
    private String fromDate;
    private String toDate;
    DefaultComboBoxModel dm = new DefaultComboBoxModel();
    DefaultComboBoxModel dm2 = new DefaultComboBoxModel();
    private String departmentFrom;
    private String shiftTo;
    private String shiftFrom;
    private String departmentTo;
    private int totalInNumber;
    private String totalInWords;
    private int sumOfPending;
    private int sumOfNetPay;
    private String cardNo;

    public ShiftRangeReport() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        connection = DBconnect.dbconnect();
        getDepartmentFrom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runningWeekCb = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        weekEndDC = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        shiftFromCombo = new javax.swing.JComboBox<>();
        shiftToCombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        departmentCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        departmentToCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cardNoTF = new javax.swing.JTextField();
        reportPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        runningWeekCb.setSelected(true);
        runningWeekCb.setText("Runing Week");
        runningWeekCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runningWeekCbActionPerformed(evt);
            }
        });

        jLabel1.setText("Week End Date");

        weekEndDC.setEnabled(false);

        jLabel2.setText("Shift From");

        jLabel3.setText("Shift To");

        shiftFromCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "A", "B", "C" }));
        shiftFromCombo.setSelectedIndex(1);

        shiftToCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "A", "B", "C" }));
        shiftToCombo.setSelectedIndex(3);

        jButton2.setText("View Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Department");

        departmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));

        jLabel7.setText("Department Range (To)");

        departmentToCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));
        departmentToCombo.setEnabled(false);

        jButton1.setText("Un-Registered");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Record Inquery");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cardNoTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardNoTFMouseClicked(evt);
            }
        });
        cardNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNoTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shiftFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runningWeekCb)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weekEndDC, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shiftToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentToCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(cardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(departmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departmentToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shiftFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shiftToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(runningWeekCb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(weekEndDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(cardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        reportPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        getContentPane().add(reportPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void runningWeekCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runningWeekCbActionPerformed
        // TODO add your handling code here:
        if (runningWeekCb.isSelected()) {
            weekEndDC.setEnabled(false);

        } else {
            weekEndDC.setEnabled(true);
        }
    }//GEN-LAST:event_runningWeekCbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        getMainFilePath();
        getData();
        getTotalInWords();
        getParam();

        showReport();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        getMainFilePath();
        //getData();
        //getTotalInWords();
        getRunningDate();
        getParam_2();

        reportPanel.removeAll();
        reportPanel.repaint();
        reportPanel.revalidate();

        try {
            JasperDesign jDesign = JRXmlLoader.load(parent + "\\src\\demo_wages\\report\\unregisteredlist.jrxml");
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, connection);
            JRViewer jRViewer = new JRViewer(jPrint);
            reportPanel.setLayout(new BorderLayout());
            reportPanel.add(jRViewer);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cardNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNoTFActionPerformed
        // TODO add your handling code here:
        recordInquery();
    }//GEN-LAST:event_cardNoTFActionPerformed

    private void cardNoTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardNoTFMouseClicked
        // TODO add your handling code here:
        cardNoTF.selectAll();
    }//GEN-LAST:event_cardNoTFMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         recordInquery();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftRangeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftRangeReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNoTF;
    private javax.swing.JComboBox<String> departmentCombo;
    private javax.swing.JComboBox<String> departmentToCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JCheckBox runningWeekCb;
    private javax.swing.JComboBox<String> shiftFromCombo;
    private javax.swing.JComboBox<String> shiftToCombo;
    private com.toedter.calendar.JDateChooser weekEndDC;
    // End of variables declaration//GEN-END:variables

    private void getMainFilePath() {
        File mainFilePath = new File("AutoRetresh.class");
        File parentLocation = new File(mainFilePath.getAbsolutePath());
        parent = parentLocation.getParent();
        //System.out.println(parent);
    }

    private void getDepartmentFrom() {

        departmentCombo.removeAllItems();
        departmentToCombo.removeAllItems();
        dm.addElement("Select One");
        dm2.addElement("Select One");
        try {
            String sql = "select * from department ORDER BY department_code ASC";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                dm.addElement(rs.getString("display_name"));
                dm2.addElement(rs.getString("display_name"));
                departmentCombo.setModel(dm);
                departmentToCombo.setModel(dm2);
            }
            statement.close();
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void getData() {
        String dept;
        if (runningWeekCb.isSelected()) {
            getRunningDate();
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            //fromDate = sdf.format(fromDateDC.getDate().getTime());
            toDate = sdf.format(weekEndDC.getDate().getTime());
        }

        dept = departmentCombo.getSelectedItem().toString();
      
        if (!dept.equals("Select One")) {
            departmentFrom = getDepartmentCode(dept);
        } else {
            JOptionPane.showMessageDialog(this, "Please Select Department...");
        }


        shiftTo = shiftToCombo.getSelectedItem().toString(); 
        shiftFrom = shiftFromCombo.getSelectedItem().toString();
        System.err.println(fromDate + "\t" + toDate);
    }

    private void getRunningDate() {
        try {
            String sql = "select * from running_week";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                fromDate = rs.getString("week_start_date");
                toDate = rs.getString("week_end_date");
            }
            System.err.println(fromDate + " " + toDate);

            statement.close();
            rs.close();
        } catch (SQLException e) {
        }
    }

    private void getParam() {
        parameter = new HashMap();
        parameter.put("weekEndDate", toDate);
        parameter.put("shift_from", shiftFrom);
        parameter.put("shift_to", shiftTo);
        parameter.put("runDept", departmentFrom);
       // parameter.put("department_2", departmentTo);
        parameter.put("totalInWords", totalInWords);
        parameter.put("pendingAmount", String.valueOf(sumOfPending));
        parameter.put("payableAmount", String.valueOf(totalInNumber));
    }

    private void showReport() {

        reportPanel.removeAll();
        reportPanel.repaint();
        reportPanel.revalidate();

        //C:\Users\MadinaJute\OneDrive\Documents\NetBeansProjects\MEGAsync\Demo_Wages\src\demo_wages\report\report1.jrxml
        try {
            JasperDesign jDesign = JRXmlLoader.load(parent + "\\src\\demo_wages\\report\\shift_wise_report.jrxml");
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, connection);
            JRViewer jRViewer = new JRViewer(jPrint);
            reportPanel.setLayout(new BorderLayout());
            reportPanel.add(jRViewer);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String getDepartmentCode(String dptDisplayName) {
        try {
            String sql = "select department_code from department where display_name='" + dptDisplayName + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                return rs.getString("department_code");
            } else {
                return null;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private void getTotalInWords() {

        try {
            String sql = "select SUM(net_payable) from sallery "
                    + "join shift_management on sallery.week_end_date=shift_management.to_date "
                    + "and sallery.r_shift=shift_management.run_shift where shift_management.ori_shift "
                    + "between '"+shiftFrom+"' and '"+shiftTo+"' and week_end_date='"+toDate+"' and "
                    + "sallery.r_department='"+departmentFrom+"' and sallery.block_status<>1";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                sumOfNetPay = rs.getInt(1);
                

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            String sql = "select SUM(net_payable) from sallery "
                    + "join shift_management on sallery.week_end_date=shift_management.to_date "
                    + "and sallery.r_shift=shift_management.run_shift where shift_management.ori_shift "
                    + "between '"+shiftFrom+"' and '"+shiftTo+"' and week_end_date='"+toDate+"' and "
                    + "sallery.r_department='"+departmentFrom+"' "
                    + "and sallery.pending_status=1";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                sumOfPending = rs.getInt(1);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        totalInNumber = sumOfNetPay - sumOfPending;
        System.err.println(sumOfNetPay + "\t" + sumOfPending + "\t" + totalInNumber);

        totalInWords = "Total Tk.(" + DigitsToWords.convert(totalInNumber) + " )Only";
        System.err.println(totalInWords);

    }

    private void getParam_2() {

        parameter = new HashMap();
        parameter.put("ewwkEndDate", toDate);

    }
    
        private void recordInquery() {
         cardNo = cardNoTF.getText();
                getMainFilePath();
        //getData();
        //getTotalInWords();
        getRunningDate();
        getParam_3();
        
       
        reportPanel.removeAll();
        reportPanel.repaint();
        reportPanel.revalidate();       
     
        try {
             JasperDesign jDesign = JRXmlLoader.load(parent+"\\src\\demo_wages\\report\\attendence_inquery.jrxml");
                        JasperReport jReport = JasperCompileManager.compileReport(jDesign);
                        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, connection);
                        JRViewer jRViewer = new JRViewer(jPrint);
                        reportPanel.setLayout(new BorderLayout());
                        reportPanel.add(jRViewer);
        } catch (Exception e) {
            e.printStackTrace();
        }
            }
        private void getParam_3() {
        parameter = new HashMap();
        parameter.put("cardNo", cardNo);
        parameter.put("start_date", fromDate);
        parameter.put("end_date", toDate);
           }

}
