/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_wages;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MJIL
 */
public class WeekSetup extends javax.swing.JFrame {

    public static Connection connection = null;
    private Date startDate = null;
    private Date endDate = null;
    private int millRuningHour = 0;
    private int hollyDayHours = 0;
    private String ori_A_run = "";
    private String ori_B_run = "";
    private String ori_C_run = "";
    private HashMap<String, String> shift;

    /**
     * Creates new form WeekSetup
     */
    public WeekSetup() {
        initComponents();
        connection = DBconnect.dbconnect();
        showDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startDateDC = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        endDateDC = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        workHourTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        weekListTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        hollydayhrsTF = new javax.swing.JTextField();
        runingWeekCB = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ori_A_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ori_B_combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ori_C_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Start Date");

        jLabel2.setText("End Date");

        jLabel3.setText("Mill Running Hours");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        weekListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        weekListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weekListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(weekListTable);

        jLabel4.setText("Holly Day Hours");

        runingWeekCB.setText("Make As Runing Week");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Shift Management"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Original Shift");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Running Shift");

        ori_A_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening", "Night" }));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("A");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("B");

        ori_B_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening", "Night" }));
        ori_B_combo.setSelectedIndex(1);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("C");

        ori_C_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening", "Night" }));
        ori_C_combo.setSelectedIndex(2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(ori_C_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ori_B_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0))
                    .addComponent(ori_A_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ori_A_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ori_B_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ori_C_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(runingWeekCB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(workHourTF, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(hollydayhrsTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startDateDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endDateDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workHourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hollydayhrsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(runingWeekCB)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(87, 87, 87))
            .addComponent(jScrollPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getData();
        if (checkWeekData()) {
            updateWeekData();
        } else {
            insertWeekData();
        }

        if (checkShiftData()) {
            updateShift();
        } else {
            insertShift();
        }

        if (runingWeekCB.isSelected()) {
            if (checkRuningWeek()) {
                updateRuningWeek();
            } else {
                insertRuningWeek();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void weekListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weekListTableMouseClicked
        // TODO add your handling code here:
        setSelectData();
    }//GEN-LAST:event_weekListTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeekSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WeekSetup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser endDateDC;
    private javax.swing.JTextField hollydayhrsTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ori_A_combo;
    private javax.swing.JComboBox<String> ori_B_combo;
    private javax.swing.JComboBox<String> ori_C_combo;
    private javax.swing.JCheckBox runingWeekCB;
    private com.toedter.calendar.JDateChooser startDateDC;
    private javax.swing.JTable weekListTable;
    private javax.swing.JTextField workHourTF;
    // End of variables declaration//GEN-END:variables

    private void getData() {
        if (startDateDC.getDate() != null) {
            startDate = new java.sql.Date(startDateDC.getDate().getTime());
        }
        if (endDateDC.getDate() != null) {
            endDate = new java.sql.Date(endDateDC.getDate().getTime());
        }
        if (!workHourTF.getText().equals("")) {
            try {
                millRuningHour = Integer.parseInt(workHourTF.getText());
            } catch (NumberFormatException e) {
            }
        }
        if (!hollydayhrsTF.getText().equals("")) {
            try {
                hollyDayHours = Integer.parseInt(hollydayhrsTF.getText());
            } catch (NumberFormatException e) {
            }
        }
        ori_A_run = ori_A_combo.getSelectedItem().toString();
        ori_B_run = ori_B_combo.getSelectedItem().toString();
        ori_C_run = ori_C_combo.getSelectedItem().toString();
        shift = new HashMap<String, String>();
        shift.put("A", ori_A_run);
        shift.put("B", ori_B_run);
        shift.put("C", ori_C_run);

    }

    private void insertWeekData() {
        if (startDate != null && endDate != null && millRuningHour != 0) {
            try {
                String sql = "insert into week_setup (week_start_date,week_end_date,mill_running_hour,hollyday_hours) "
                        + "values(?,?,?,?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setDate(1, startDate);
                statement.setDate(2, endDate);
                statement.setInt(3, millRuningHour);
                statement.setInt(4, hollyDayHours);
                statement.executeUpdate();
                showDataTable();
                JOptionPane.showMessageDialog(this, "Week setup Successful");

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private boolean checkWeekData() {
        try {
            String sql = "select* from week_setup where week_start_date='" + startDate + "' and week_end_date='" + endDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private void updateWeekData() {
        try {
            String sql = "update week_setup set mill_running_hour = '" + millRuningHour + "',"
                    + "hollyday_hours = '" + hollyDayHours + "'"
                    + " where week_start_date='" + startDate + "' and week_end_date ='" + endDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();
            showDataTable();
            JOptionPane.showMessageDialog(this, "Update Successful");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDataTable() {
        try {
            String sql_1 = "select week_start_date,week_end_date,mill_running_hour,hollyday_hours"
                    + " from week_setup ORDER BY week_start_date DESC";
            PreparedStatement st = connection.prepareStatement(sql_1);
            ResultSet rs_1 = st.executeQuery();
            weekListTable.setModel(DbUtils.resultSetToTableModel(rs_1));

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void setSelectData() {
        int row = weekListTable.getSelectedRow();
        String tableClicked = (weekListTable.getModel().getValueAt(row, 0).toString());

        try {
            String sql = "select * from week_setup where week_start_date='" + tableClicked + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                startDateDC.setDate(rs.getDate("week_start_date"));
                endDateDC.setDate(rs.getDate("week_end_date"));
                workHourTF.setText(String.valueOf(rs.getInt("mill_running_hour")));
                hollydayhrsTF.setText(String.valueOf(rs.getInt("hollyday_hours")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        getShiftData(tableClicked);
    }

    private void insertRuningWeek() {
        if (startDate != null && endDate != null && millRuningHour != 0) {
            try {
                String sql = "insert into running_week (week_start_date,week_end_date,mill_running_hour,hollyday_hours) "
                        + "values(?,?,?,?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setDate(1, startDate);
                statement.setDate(2, endDate);
                statement.setInt(3, millRuningHour);
                statement.setInt(4, hollyDayHours);
                statement.executeUpdate();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }

    private boolean checkRuningWeek() {
        try {
            String sql = "select* from running_week";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private void updateRuningWeek() {
        try {
            String sql = "update running_week set mill_running_hour = '" + millRuningHour + "',"
                    + "hollyday_hours = '" + hollyDayHours + "',"
                    + "week_start_date = '" + startDate + "',"
                    + "week_end_date = '" + endDate + "' "
                    + " where id='1'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateShift() {
        for (String i : shift.keySet()) {
            System.out.println("Name: " + i + " Age: " + shift.get(i));
            try {
                String sql = "update shift_management set ori_shift = '" + i + "',"
                        + "run_shift = '" + shift.get(i) + "'"
                        + " where from_date='" + startDate + "' and to_date='" + endDate + "' and "
                        + "ori_shift='" + i + "' ";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.executeUpdate();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void insertShift() {

        for (String i : shift.keySet()) {
            //System.out.println("Name: " + i + " Age: " + shift.get(i));
            try {
                String sql = "insert into shift_management (from_date,"
                        + "to_date,ori_shift,run_shift) "
                        + "values(?,?,?,?)";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.setDate(1, startDate);
                statement.setDate(2, endDate);
                statement.setString(3, i);
                statement.setString(4, shift.get(i));
                statement.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private boolean checkShiftData() {
        try {
            String sql = "select* from shift_management where "
                    + "from_date='" + startDate + "' and "
                    + "to_date='" + endDate + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private void getShiftData(String tableClicked) {
        try {
            String sql = "select * from shift_management where from_date='" + tableClicked + "'";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {

                if(rs.getString("ori_shift").equals("A")){
                    ori_A_combo.setSelectedItem(rs.getString("run_shift"));
                }
                if(rs.getString("ori_shift").equals("B")){
                    ori_B_combo.setSelectedItem(rs.getString("run_shift"));
                }
                if(rs.getString("ori_shift").equals("C")){
                    ori_C_combo.setSelectedItem(rs.getString("run_shift"));
                }
            }
        } catch (Exception e) {
        }
    }
}
